
server:
    port: 9091

logging:
    level:
        cxy.example: TRACE

eureka:
    instance:
        hostname: eureka-svr1
    client:
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
            defaultZone: http://eureka-svr0:9090/eureka/,http://eureka-svr2:9092/eureka/

spring:
    application:
        name: eureka-server
