
server:
    port: 9092

logging:
    level:
        cxy.example: TRACE

eureka:
    instance:
        hostname: eureka-svr2
    client:
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
            defaultZone: http://eureka-svr0:9090/eureka/,http://eureka-svr1:9091/eureka/

spring:
    application:
        name: eureka-server
