
server:
    port: 9090

logging:
    level:
        cxy.example: TRACE

eureka:
    instance:
        hostname: eureka-svr0
    client:
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
            defaultZone: http://eureka-svr1:9091/eureka/,http://eureka-svr2:9092/eureka/

spring:
    application:
        name: eureka-server
